/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LibGotchiLending,
  LibGotchiLendingInterface,
} from "../LibGotchiLending";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
    ],
    name: "GotchiLendingAdd",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "tokenId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "initialCost",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "period",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8[3]",
        name: "revenueSplit",
        type: "uint8[3]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "originalOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "thirdParty",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "whitelistId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "revenueTokens",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timeCreated",
        type: "uint256",
      },
    ],
    name: "GotchiLendingAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "GotchiLendingCancel",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "tokenId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "initialCost",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "period",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8[3]",
        name: "revenueSplit",
        type: "uint8[3]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "originalOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "thirdParty",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "whitelistId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "revenueTokens",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timeCanceled",
        type: "uint256",
      },
    ],
    name: "GotchiLendingCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "tokenAddresses",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "GotchiLendingClaim",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "tokenId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "initialCost",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "period",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8[3]",
        name: "revenueSplit",
        type: "uint8[3]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "originalOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "thirdParty",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "whitelistId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "revenueTokens",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timeClaimed",
        type: "uint256",
      },
    ],
    name: "GotchiLendingClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
    ],
    name: "GotchiLendingEnd",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "tokenId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "initialCost",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "period",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8[3]",
        name: "revenueSplit",
        type: "uint8[3]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "originalOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "thirdParty",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "whitelistId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "revenueTokens",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timeEnded",
        type: "uint256",
      },
    ],
    name: "GotchiLendingEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
    ],
    name: "GotchiLendingExecute",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "listingId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "tokenId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "initialCost",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "period",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8[3]",
        name: "revenueSplit",
        type: "uint8[3]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "originalOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "thirdParty",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "whitelistId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "revenueTokens",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timeAgreed",
        type: "uint256",
      },
    ],
    name: "GotchiLendingExecuted",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122080cdb09bf289fcbff4c8c030c40ca130d0878d8488c05e2aa75be8eba0c309cd64736f6c63430008010033";

export class LibGotchiLending__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibGotchiLending> {
    return super.deploy(overrides || {}) as Promise<LibGotchiLending>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibGotchiLending {
    return super.attach(address) as LibGotchiLending;
  }
  connect(signer: Signer): LibGotchiLending__factory {
    return super.connect(signer) as LibGotchiLending__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibGotchiLendingInterface {
    return new utils.Interface(_abi) as LibGotchiLendingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibGotchiLending {
    return new Contract(address, _abi, signerOrProvider) as LibGotchiLending;
  }
}
