/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LibWhitelistInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "WhitelistAccessRightSet(uint32,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WhitelistAccessRightSet"): EventFragment;
}

export type WhitelistAccessRightSetEvent = TypedEvent<
  [number, BigNumber, BigNumber] & {
    whitelistId: number;
    actionRight: BigNumber;
    accessRight: BigNumber;
  }
>;

export class LibWhitelist extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LibWhitelistInterface;

  functions: {};

  callStatic: {};

  filters: {
    "WhitelistAccessRightSet(uint32,uint256,uint256)"(
      whitelistId?: BigNumberish | null,
      actionRight?: BigNumberish | null,
      accessRight?: BigNumberish | null
    ): TypedEventFilter<
      [number, BigNumber, BigNumber],
      { whitelistId: number; actionRight: BigNumber; accessRight: BigNumber }
    >;

    WhitelistAccessRightSet(
      whitelistId?: BigNumberish | null,
      actionRight?: BigNumberish | null,
      accessRight?: BigNumberish | null
    ): TypedEventFilter<
      [number, BigNumber, BigNumber],
      { whitelistId: number; actionRight: BigNumber; accessRight: BigNumber }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
